Iter13
DimaKoz/practicummetrics pull request #14
Opened 2023-06-11 21:48 UTC by DimaKoz

2023-06-16 08:24 UTC, arttet requested changes
Please add indexes and migrations

2023-06-16 08:24 UTC, arttet commented on Makefile
> +	golangci-lint run -v --enable-all --disable gochecknoglobals --disable paralleltest --disable exhaustivestruct --disable depguard --disable wsl
You need to use config for linters.

2023-06-16 08:24 UTC, arttet commented on Makefile
> +	gofumpt -l -w .
You can add `gofmt` either

2023-06-17 15:05 UTC, DimaKoz commented on Makefile
> +	gofumpt -l -w .
done

2023-06-17 15:32 UTC, DimaKoz commented on Makefile
> +	golangci-lint run -v --enable-all --disable gochecknoglobals --disable paralleltest --disable exhaustivestruct --disable depguard --disable wsl
done

2023-06-21 11:08 UTC, merged