Iter18
DimaKoz/practicummetrics pull request #23
Opened 2023-08-22 21:50 UTC by DimaKoz

2023-10-21 13:51 UTC, s-shpak requested changes

2023-10-21 13:51 UTC, s-shpak commented on Makefile
> +cover:
1. Добавь, пожалуйста, вывод общего покрытия кода
2. Ты намеренно не используешь .PHONY ?

2023-10-21 13:51 UTC, s-shpak commented on cmd/agent/main.go
> +	/*	go func() {
Deadcode следует убрать из PR

2023-10-21 13:51 UTC, s-shpak commented on cmd/server/main.go
> +	logger := zap.Must(zap.NewDevelopment())
Зачем здесь использовать `Must` вместо явной обработки ошибки?

2023-10-21 13:51 UTC, s-shpak commented on cmd/server/main.go
> +	zap.ReplaceGlobals(logger)
1. Я бы не стал подменять глобальный логгер, а передавал инстансы логгера явным образом: разрешить использование глобального логгера внутри приложения - плохая идея, потому что тебе будет сложно изменить его поведение
2. Если функция возвращает какой-то объект, но ты его не используешь, то его стоит проигнорировать явно. В golangci-lint есть для этого настройка

2023-10-21 13:51 UTC, s-shpak commented on cmd/server/main.go
> +	var err error
Зачем объявлять здесь переменную явно?

2023-10-21 13:51 UTC, s-shpak commented on doc.go
> +// # Смотрите больше информации по курсу смотрите:
```suggestion
// # Смотрите больше информации по курсу:
```

2023-10-21 13:51 UTC, s-shpak commented on internal/agent/gather/gatherer.go
> +func collectUintMetricsVariant(rtm *runtime.MemStats, result *[]model.MetricUnit) error {
Зачем передавать указатель на слайс, а не просто вернуть новый слайс из функции?

2023-10-21 13:51 UTC, s-shpak commented on internal/agent/gather/gatherer.go
> +	utilizationStValue := fmt.Sprintf("%v", utilization[0]) // strconv.FormatFloat(utilization[0], 'f', 2, 64)
да, это нужно переписать на `strconv` - это более эффективный способ конверсии. Или это чтобы бенч показывал прирост производительности? :)

2023-10-21 13:51 UTC, s-shpak commented on internal/agent/gather/gatherer.go
> +func GetMetricsVariant(resultChan chan *[]model.MetricUnit, errChan chan error) {
1. Не вижу смысла использовать указатель на массив
2. Можно указать более специализированный тип канала (на чтение или на запись), что упростит понимание, что именно делает функция, и позволит избежать ошибок в дальнейшем

2023-10-21 13:51 UTC, s-shpak commented on internal/common/config/configer_bench_internal_test.go
> +func BenchmarkConfigStringVariantBuffer(b *testing.B) {
Бенчи стоит организовать по-другому: т.к. deadcode не должен попадать в проект, я бы измерил производительность "старого" решения, сохранил бы ее профиль где-то, а потом добавил инструкции как прогнать бенчи для "нового" решения и сравнить со старым

2023-10-22 10:07 UTC, DimaKoz commented on Makefile
> +cover:
1. Вывод "Total:" добавил.
2. .PHONY - мне непринципиально его наличие. Добавил

2023-10-22 10:13 UTC, DimaKoz commented on doc.go
> +// # Смотрите больше информации по курсу смотрите:
Поправил

2023-10-26 13:48 UTC, DimaKoz commented on cmd/server/main.go
> +	logger := zap.Must(zap.NewDevelopment())
Явное лучше неявного :)

2023-10-26 13:49 UTC, DimaKoz commented on cmd/server/main.go
> +	var err error
Явное лучше неявного :) ?

2023-10-29 23:33 UTC, DimaKoz commented on internal/agent/gather/gatherer.go
> +	utilizationStValue := fmt.Sprintf("%v", utilization[0]) // strconv.FormatFloat(utilization[0], 'f', 2, 64)
Согласен

goos: linux
goarch: amd64
pkg: github.com/DimaKoz/practicummetrics/internal/agent/gather
cpu: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
BenchmarkUtilizationConvertValue
BenchmarkUtilizationConvertValue/Sprintf()
BenchmarkUtilizationConvertValue/Sprintf()-12         	         7472413	       157.1 ns/op	      32 B/op	       2 allocs/op
BenchmarkUtilizationConvertValue/FormatFloat()
BenchmarkUtilizationConvertValue/FormatFloat()-12     	 8379586	       142.1 ns/op	      28 B/op	       2 allocs/op

2023-10-30 14:29 UTC, s-shpak commented on cmd/server/main.go
> +	var err error
Получается, двойные стандарты :)

2023-10-31 12:49 UTC, s-shpak approved these changes

2023-10-31 13:34 UTC, merged