Iter5
DimaKoz/practicummetrics pull request #5
Opened 2023-04-09 22:24 UTC by DimaKoz

2023-04-13 12:55 UTC, mshogin requested changes
В целом очень круто. Код понятный. Проделана огромная работа. Есть несколько моментов для улучшения.

2023-04-13 12:55 UTC, mshogin commented on cmd/server/main.go
> +const defaultAddress = "localhost:8080"
предлагаю отправить в model.config.go

2023-04-13 12:55 UTC, mshogin commented on internal/common/model/config.go
> +package model
предлагаю type Config отправить в package config

2023-04-13 12:55 UTC, mshogin commented on internal/common/config/configer.go
> +func AgentInitConfig(cfg *model.Config,
предлагаю 

1. model.Config перенести в этот пакет
2. этот метод переименовать в LoadConfig/CreateConfig/Load/Create 
3. изменить сигнатуру функции на 
```
func LoadConfig() (Config, error)
```
4. Ошибки в функциях processEnv and processFlags обработать и вернуть в LoadConfig
5. Обработка ошибок должна быть специфицирована
```
return err   // bad
return fmt.Errorf("cannot convert poll interval to int: %w", err)   // good
```
6. Все defaults перенести в этот пакет и обьявить как константы

2023-04-13 12:55 UTC, mshogin commented on internal/server/handler/roothandler.go
> +		c.Error(errHTTP)
из документации 
```
		// Error invokes the registered global HTTP error handler. Generally used by middleware.
		// A side-effect of calling global error handler is that now Response has been committed (sent to the client) and
		// middlewares up in chain can not change Response status code or Response body anymore.
		//
		// Avoid using this method in handlers as no middleware will be able to effectively handle errors after that.
		Error(err error)
```
предлагаю последовать рекомендации и не использовать этот метод
можно заменить на 
```
	return c.String(http.StatusNotFound, "wrong url")
```

во всех хендлерах

2023-04-13 12:55 UTC, mshogin commented on internal/server/handler/roothandler.go
> +	if c.Request().URL.Path != "/" {
это условие не выполнится т.к. мы зарегистрировали хендлер как
```
	e.GET("/", handler.RootHandler)
```
предлагаю удалить DeadCode

2023-04-13 12:55 UTC, mshogin commented on internal/common/repository/memstorage.go
> +		instanceMemSt = MemStorage{}
предлагаю использовать более Go-way
```
		instanceMemSt = MemStorage{
			storage: make(map[string]model.MetricUnit, 0),
		}
```

2023-04-13 12:55 UTC, mshogin commented on internal/common/repository/memstorage.go
> +func InitMemStorage() {
Предлагаю просто удалить этот метод и сделать 
   ```
   var instanceMemSt = MemStorage{
	storage: make(map[string]model.MetricUnit, 0),
}
```

2023-04-13 12:55 UTC, mshogin commented on internal/common/repository/memstorage.go
> +var instanceMemSt MemStorage
рекомендация: переименовать в memStorage

2023-04-13 12:55 UTC, mshogin commented on internal/common/repository/memstorage.go
> +var lockMemSt = &sync.Mutex{}
практика именования примитив синхронизации это добаление суфикса Sync к имени переменной которую будем синхронизовать
```
var memStorage = MemStorage
var memStorageSync = &sync.Mutex{} 
```

2023-04-13 12:55 UTC, mshogin commented on internal/common/repository/memstorage.go
> +		result = &model.MetricUnit{
предлагаю в MetricUnit сделать метод Clone и использовать его

2023-04-13 12:55 UTC, mshogin commented on internal/common/repository/memstorage.go
> +		newMetric, err := model.NewMetricUnit(v.Type, v.Name, v.Value)
если появится Clone то здесь будет просто 
```
result = appent(result, v.Clone())
```

2023-04-13 12:55 UTC, mshogin commented on internal/common/model/metricunit.go
> +	ValueI int64
ValueI -> ValueInt
ValueF -> ValueFloat

2023-04-13 12:55 UTC, mshogin commented on internal/server/handler/updatehandler.go
> +func processPath(path string) (*model.MetricUnit, *error2.RequestError) {
предлагаю перейти на 
https://echo.labstack.com/guide/#path-parameters

2023-04-13 12:55 UTC, mshogin commented on internal/server/handler/updatehandler.go
> +	repository.AddMetricMemStorage(*mu)
необходимо сделать что бы либо все методы работали с MetricUnit либо с *MetricUnit

2023-04-13 12:55 UTC, mshogin commented on internal/common/repository/memstorage.go
> +func AddMetricMemStorage(mu model.MetricUnit) {
minor: предлагаю переименовать в AddMetric

2023-04-13 12:55 UTC, mshogin commented on internal/common/repository/memstorage.go
> +func GetMetricsMemStorage() []model.MetricUnit {
предлагаю переименовать в GetAllMetrics

2023-04-13 12:55 UTC, mshogin commented on internal/server/handler/valuehandler.go
> +	name, err := getNameFromPath(c.Request().URL.Path)
предлагаю перейти на
https://echo.labstack.com/guide/#path-parameters

2023-04-13 12:55 UTC, mshogin commented on cmd/agent/main.go
> +	go sleepingKiller()
предлагаю это удалить

2023-04-13 12:55 UTC, mshogin commented on cmd/agent/main.go
> +	tickerGathering.Stop()
перенести в метсто обьявления тикера с defer
```
	tickerGathering := time.NewTicker(time.Duration(cfg.PollInterval) * time.Second)
        defer tickerGathering.Stop()
```

2023-04-13 12:55 UTC, mshogin commented on internal/agent/gather/gatherer.go
> +	var err *error2.RequestError
предлагаю использовать стандартную ошибку
и все ошибки необходимо обработать и пецифицировать
```
if err != nil {
return fmt.Errorf("cannot get runtime.Alloc: %w", err)
}
```

2023-04-13 12:55 UTC, mshogin commented on internal/agent/gather/gatherer.go
> +func GetMetrics() *[]model.MetricUnit {
предлагаю вынести сбор runtime метрик в отдальную функцию и сделать из GetMetrics что то вроде
```
func GetMetrics() ([]metrics, error) {
    metrics, err := collectRuntimeMetrics()
    if err != nil { return ....

    m, err := collectSystemMetrics()
    if err != nil { return ....

    metrics = append(metrics, ...m)
    
    return metrics, nil
}
    ````

2023-04-13 12:55 UTC, mshogin commented on internal/agent/send/sender.go
> +var Address string = "http://localhost:8080"
предлагаю отправить это в конфиг

2023-04-13 12:55 UTC, mshogin commented on internal/agent/send/sender.go
> +		url := "http://" + Address + "/update/" + prepPathByMetric(unit)
предлагаю вынести простроение URL в функцию getURL() и заиспользовать url.URL из net/url
```
	u := url.URL{
		Scheme: "http",
	}
	u.Host = "localhost"
	u.Path = "/adfasd/asdfs"
	fmt.Printf("%s\n", u.String()) // output for debug
```

2023-04-13 12:55 UTC, mshogin commented on internal/agent/send/sender.go
> +package send
предлагаю назвать пакет sender
send - это глагол

Необходимо тесты написать

2023-04-13 12:55 UTC, mshogin commented on internal/server/middleware/methodchecker.go
> +package middleware
это можно удалить

2023-04-14 18:17 UTC, DimaKoz commented on internal/agent/gather/gatherer.go
> +	var err *error2.RequestError
В зависимости от ошибки при создании MetricUnit могут быть разные ответы сервера(StatusCode), поэтому нужна своя ошибка и отказываться не хотелось бы.
При сборе метрик, вроде, статус ответа не имеет значения, можно их игнорировать и создавать стандартную для этого места с описанием метрики.
Как лучше поступить?

2023-04-17 08:42 UTC, mshogin requested changes
Здорово! После последних изменений мы можем приступить к проработке архитектуры приложения.

Я иногда даю пример кода как должно выглядеть.
Очень ВАЖНО!!! что бы ты сам руками все набирал, это важно что бы все это запомнилось.
Пожалуйста не делай copy-past

2023-04-17 08:42 UTC, mshogin commented on cmd/agent/main.go
> +				fmt.Println("sigs:", t)
1. _ = <- sigs нам t не нужно
2. fmt.Println - удалить

2023-04-17 08:42 UTC, mshogin commented on cmd/agent/main.go
> +				fmt.Println(err1)
предлагаю
1. `t` - удалить, оно нам не нужно
2. fmt.Println("gathering info Tick at", t) - удалить
3. ошибку обработать 
```
+				if err != nil {
+					log.Fatalf("cannot collect metrics: %s", err)
+				}
```

2023-04-17 08:42 UTC, mshogin commented on cmd/agent/main.go
> +				fmt.Println("sending info Tick at", t)
предлагаю
1. заменить на _ = <- tiecker....
2. Println удалить

2023-04-17 08:42 UTC, mshogin commented on internal/agent/gather/gatherer.go
> +		}
предлагаю
1. в случае возникновения ошибки сразу завершать выполнение и выходить с ошибкой.
2. удалить проверку на && m != model.EmptyMetric, достаточно того факта что есть ошибка
```
        value := getFieldValue(rtm, name)
        if m, err := model.NewMetricUnit(model.MetricTypeGauge, name, value); err == nil {
            result = append(result, m)
        } else {
            return nil, fmt.Errorf("cannot create %q metric: %w", name, err)
        }
```
привести к этому виду все метрики из collectOtherTypeMetrics

2023-04-17 08:42 UTC, mshogin commented on internal/agent/gather/gatherer.go
> +	}
предлагаю ошибки обрабатывать, специфицировать и заканчивать выполнение по мере их появления

сразу напишу что я очень! рекомендую избавится от типа error2.RequestError
да, придется тесты переделать, но нам эта ошибка будет только мешать развивать приложение

в итоге должно получится
```
	result, err := collectUint64Metrics(&rtm)
	if err != nil {
		return nil, fmt.Errorf("cannot collectUint64Metrics: %w:", err)
	}
```
вызов метода collectOtherTypeMetrics соответственно

2023-04-17 08:42 UTC, mshogin commented on internal/agent/sender/sender.go
> +		client := resty.New()
предлагаю вынести создание клиента за скоуп цикла

2023-04-17 08:42 UTC, mshogin commented on internal/agent/sender/sender.go
> +		}
я бы сделал так
```
		if err != nil {
			log.Errorf("cannot send metric %v: %s", unit, err)
		}
```
твой вариант ок, только надо заменить fmt.Print на log.Print

2023-04-17 08:42 UTC, mshogin commented on internal/common/config/configer.go
> +		return nil, fmt.Errorf(errDesc)
return nil, errors.New("unsupported config type")

2023-04-17 08:42 UTC, mshogin commented on internal/common/config/configer.go
> +var getEnv = processEnv
можно сделать так
```
var processEnv = func(config *Config) error {
	err := env.Parse(config)
	if err != nil {
		return fmt.Errorf("couldn't parse an enviroment, error: %w", err)
	}
	return nil
}
```
и везде заменить getEnv на processEnv

2023-04-17 08:42 UTC, mshogin commented on internal/common/config/configer.go
> +	}
это эквивалентно следующему
```
	if err := processEnv(cfg); err != nil {
		return nil, fmt.Errorf("cannot process ENV variables: %w", err)
	}
	if err := processFlags(cfg, configType); err != nil {
		return nil, fmt.Errorf("cannot process flags variables: %w", err)
	}
```

2023-04-17 08:42 UTC, mshogin commented on internal/common/config/configer.go
> +	}
рекомендация (не обязательно делать)
я бы сделал сейчас так
```
	flag2.StringVarP(&address, "a", "a", "", "")
	flag2.StringVarP(&pFlag, "p", "p", "", "")
	flag2.StringVarP(&rFlag, "r", "r", "", "")
```
на работоспособность кода это не повлияет

но вообще, я бы сделал 2 конфига AgentConfig and ServerConfig

но, опять же, это рекомендация, можно не делать

2023-04-17 08:42 UTC, mshogin commented on internal/common/config/configer_test.go
> +	defer func() { getEnv = old }()
рекомендация (не обязательно выполнять)
я обычно называю не old, а varNameOrig
```
	processEnvOrig := processEnv
	defer func() { processEnv = processEnvOrig }()
```

2023-04-17 08:42 UTC, mshogin commented on cmd/agent/main.go
> +	}
1. Общее правило не использовать семейство функций
```
fmt.PrintXXX
```
они используются для отладки. Прелагаю удалить все fmt.Println

2. Вместо
```
fmt.Println(err)
os.Exit(1)
```
предлагаю использовать
```
    if err != nil {
        log.Fatalf("cannot create config: %s", err)
    }
```

3. Очень важно!!! - всегда специфицируй ошибки
```
log.Fatal(err) // bad
log.Fatalf("cannot create config: %s", err) // good
...
return nil, err // bad
return EmptyMetric, fmt.Errorf("cannot parse gauge value: %w", err) // good
```
следуя этому прваилу, в случае получения ошибки мы будем иметь полное описание что, где и почему случилось. Это позволит находить проблемный код за пару минут, независимо от размера и сложности кодовой базы

2023-04-17 08:42 UTC, mshogin commented on cmd/server/main.go
> +		os.Exit(1)
+		log.Fatalf("cannot create config: %s", err)

2023-04-17 08:42 UTC, mshogin commented on cmd/server/main.go
> +		os.Exit(1)
if err := e.Start(cfg.Address); err != nil {
		log.Fatalf("cannot start server: %s", err)

2023-04-17 08:42 UTC, mshogin commented on cmd/server/main.go
> +	e.POST("/value/*", handler.ValueHandler)
это лишний handler, предлагаю удалить

2023-04-17 08:42 UTC, mshogin commented on internal/server/handler/updatehandler.go
> +	}
processPath лишнее здесь, echo сам берет на себя проверку path
предлагаю удалить processPath и привести метод к виду  
```
	mType := c.Param("type") // 
        ......             Param("name")
                           Param("value")

	mu, err := model.NewMetricUnit(mType, mName, mValue)
	if err != nil {
		return c.String(http.StatusBadRequest, fmt.Sprintf("cannot create metric: %s", err))
	}

```

2023-04-17 08:42 UTC, mshogin commented on internal/server/handler/valuehandler.go
> +	fmt.Println(c.ParamNames(), c.ParamValues())
предлагаю это удалить отладку

2023-04-17 08:42 UTC, mshogin commented on internal/server/handler/valuehandler.go
> +	}
это условие никогда не выполнится, за это отвечает echo 
предлагаю удалить

2023-04-17 08:42 UTC, mshogin commented on internal/server/handler/valuehandler.go
> +	return nil
предлагаю упростить до вида
```
	return c.String(http.StatusOK, mu.Value)
```

2023-04-17 08:42 UTC, mshogin commented on internal/server/handler/valuehandler.go
> +	}
это предлагаю переделать к виду
```
	mu, err := repository.GetMetricByName(name)
	if err != nil {
		return c.String(http.StatusNotFound, fmt.Sprintf("cannot find metric: %s", err))
	}
```
про repository отдельно напишу

2023-04-17 08:42 UTC, mshogin commented on internal/common/repository/memstorage.go
> +	return result
предлагаю переработать к виду
```
	if found, ok := memStorage.storage[name]; ok {
		return found.Clone(), nil
 	}
	return model.MetricUnit{}, fmt.Errorf("no metric %q in storage", name)
```

соответственно переделать сигнатуру функции на 
```
GetMetricByName(name string) (model.MetricUnit, error)
```

2023-04-17 08:42 UTC, mshogin commented on internal/common/model/metricunit.go
> +}
предлагаю удалить кастомную ошибку. Нет смысла ее заводить.
нам нет функциональной необходимости заводить эти кастомные ошибки.
Это активно используется в тестах, однако в нашем случае нам не так важно по какой именно причине ошибка, нам важно какие условия приводят к ошибке.

Предлагаю привести код к виду
```
func NewMetricUnit(typ string, name string, value string) (MetricUnit, error) {
	if typ != MetricTypeGauge && typ != MetricTypeCounter {
		return EmptyMetric, errors.New("unknown type")
	}
	if name == "" || value == "" {
		return EmptyMetric, errors.New("to create a metric you must provide `name` and `value`")
	}
```

2023-04-17 16:51 UTC, DimaKoz commented on cmd/agent/main.go
> +				fmt.Println("sigs:", t)
готово

2023-04-17 16:52 UTC, DimaKoz commented on cmd/agent/main.go
> +				fmt.Println(err1)
готово

2023-04-17 16:54 UTC, DimaKoz commented on cmd/agent/main.go
> +				fmt.Println("sending info Tick at", t)
готово, хотя применил такую конструкцию `case <-tickerReport.C:`

2023-04-17 16:55 UTC, DimaKoz commented on internal/agent/sender/sender.go
> +		client := resty.New()
готово

2023-04-17 16:59 UTC, DimaKoz commented on internal/agent/sender/sender.go
> +		}
`log.Errorf` -  не нашёл у стандартного пакета `log`,   заменил  `fmt` -> `log`

2023-04-17 17:01 UTC, DimaKoz commented on cmd/agent/main.go
> +	}
готово(для main)

2023-04-17 17:03 UTC, DimaKoz commented on cmd/server/main.go
> +		os.Exit(1)
done

2023-04-17 17:05 UTC, DimaKoz commented on cmd/server/main.go
> +	e.POST("/value/*", handler.ValueHandler)
это был рудимент, чтоб проходить автотесты, которые были с ошибками, тесты в шаблоне на гитхабе потом поправили, а рудимент остался, удалил.

2023-04-17 17:07 UTC, DimaKoz commented on cmd/server/main.go
> +		os.Exit(1)
готово

2023-04-17 17:09 UTC, DimaKoz commented on internal/server/handler/updatehandler.go
> +	}
`processPath` больше нет

2023-04-17 17:11 UTC, DimaKoz commented on internal/server/handler/valuehandler.go
> +	fmt.Println(c.ParamNames(), c.ParamValues())
готово

2023-04-17 17:15 UTC, DimaKoz commented on internal/server/handler/valuehandler.go
> +	return nil
готово

2023-04-17 17:35 UTC, DimaKoz commented on internal/common/config/configer_test.go
> +	defer func() { getEnv = old }()
готово. defer убрал совсем:
```
        processEnvOrig := processEnv
	t.Cleanup(func() {
		...
		processEnv = processEnvOrig
	})

```

2023-04-17 17:36 UTC, DimaKoz commented on internal/common/config/configer.go
> +var getEnv = processEnv
готово

2023-04-17 17:36 UTC, DimaKoz commented on internal/common/config/configer.go
> +		return nil, fmt.Errorf(errDesc)
готово

2023-04-17 22:04 UTC, DimaKoz commented on internal/common/repository/memstorage.go
> +	return result
готово

2023-04-17 22:05 UTC, DimaKoz commented on internal/server/handler/valuehandler.go
> +	}
готово

2023-04-17 22:05 UTC, DimaKoz commented on internal/server/handler/valuehandler.go
> +	}
готово

2023-04-17 22:05 UTC, DimaKoz commented on internal/common/config/configer.go
> +	}
готово

2023-04-18 15:47 UTC, DimaKoz commented on internal/common/config/configer.go
> +	}
>>но вообще, я бы сделал 2 конфига AgentConfig and ServerConfig

разбил их на два конфига

2023-04-18 18:03 UTC, DimaKoz commented on internal/agent/gather/gatherer.go
> +	}
готово, хотя пока всё ещё берём оригинальную ошибку из `error2.RequestError`, чтобы было легче в дальнейшем удалить `error2.RequestError`

2023-04-18 18:03 UTC, DimaKoz commented on internal/agent/gather/gatherer.go
> +		}
так даже проще, готово

2023-04-18 18:40 UTC, DimaKoz commented on internal/common/model/metricunit.go
> +}
удалил `RequestError`

2023-04-19 07:30 UTC, mshogin requested changes
Отлично мы на финишной прямой! Там два маленьких момента требуется поправить и все будет готово.
Ревью: https://disk.yandex.ru/i/RYsE-9Zs9OzWxQ
рекомендую смотреть на скорости 1.5х-2х
Отправлено на доработку

2023-04-19 13:12 UTC, mshogin approved these changes
Супер! Здорово поработали. Спасибо.

2023-04-19 16:28 UTC, merged